services:
  gitlab-webhook:
    # Build from DockerHub's image.
    image: galarzaa90/gitlab-discord-webhook:latest
    # Comment image, and uncomment build to build locally.
#    build:
#      context: .
    volumes:
      - ./config.ini:/app/config.ini
    ports:
      - 7400:7400
